services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: MySQL
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/store:/var/lib/mysql
    networks:
      - board

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/Board_t?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: AZsx!@#$1739
    networks:
      - board

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    networks:
      - board

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - ./redis/data:/data
    networks:
      - board


networks:
  board: