services:
  db:
    build:
      context: ./docker-test-db
      dockerfile: Dockerfile
    ports:
      - 3307:3306
    volumes:
      - ./docker-test-db/store:/var/lib/mysql
    networks:
      - network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/Board_t?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: AZsx!@#$1739
    networks:
      - network

networks:
  network: