services:
  mysqldb:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=boarddb
    ports:
      - "3307:3306"

volumes:
  mysql-compose-volume: